### ISSUE TITLE
Duplicate Route Names

### ISSUE THREAD

**Issue by dcomartin** [horsdal/Nancy.Linker#14]
If you have multiple routes with the same name, generating a link throws an `InvalidOperationException: Sequence contains more than one matching element.`

Repro: https://gist.github.com/dcomartin/43f729d64a44b0248f5ceab7ca4c1096

Thinking this should do a dup check.  However in my own code base I'm thinking I actually want to have a test to prevent it.  Not sure if having a dup check method that could be added to bootstrapper?

**Comment by horsdal** [comment]
A better exception message is definitely called for.

As for a dup check, I think that makes more sense in Nancy.

**Comment by horsdal** [comment]
Here's a better exception message: https://github.com/horsdal/Nancy.Linker/commit/cd472a2e3252eb03a4e18a82d319f8e657a954fb

That should give you e.g. `Nancy.Linker found two routes called "TestRoute", but can only create links for uniquely named routes`
