### ISSUE TITLE
Passing query string parameters?

### ISSUE THREAD

**Issue by sakopov** [horsdal/Nancy.Linker#15]
I'm trying to pass a couple of query string parameters used for pagination, but they're not getting added to the URI.

The two parameters are `new { skip = skip, limit = limit }`

And I added the URI filter to ApplicationStartup

`container.Register<UriFilter>(new PassthroughUriFilter(new[] { "skip", "limit" }));`

I don't have the actual parameters defined anywhere in the path of the endpoint. I'm assuming that's ok. Is there anything else I'm missing?

**Comment by horsdal** [comment]
> The two parameters are new { skip = skip, limit = limit }

I'm not exactly sure what you mean. Could post code that misbehaves?

In the mean time maybe this test shows how it works https://github.com/horsdal/Nancy.Linker/blob/master/src/Nancy.Linker.Tests/PassthroughUriFilterTests.cs#L69

**Comment by sakopov** [comment]
I have a GET endpoint /components which requires 2 query string parameters - skip & limit - used for paging the returned data set. I'm using Nancy.Linker to add the self link to the resource/model which contains the resulted data set the client requested. The self link is basically the link that the client used to retrieve the resulted data set including skip & limit parameters. 

The problem is Nancy.Linker doesn't add skip & limit parameters to the URL.

` resourceLinker.BuildAbsoluteUri(_nancyContext, "componentsRoute", { skip = 1, limit = 5}).AbsoluteUri;`

So I only get `/components` instead of `/components?skip=1&limit=5`

Honestly, I don't even know if Linker supports query strings. There is something called "
Query Parameter Passthrough" but I don't quite understand what this is supposed to do. 

So in the meantime I'm simply adding query string parameters manually using something like this:

```
private static string BuildPaginatedLink(Uri path, int skip, int limit)
        {
            var builder = new UriBuilder(path);
            var queryString = HttpUtility.ParseQueryString(builder.Query);
            queryString.Add("skip", skip.ToString());
            queryString.Add("limit", limit.ToString());
            builder.Query = queryString.ToString();

            return builder.ToString();
        }
```

**Comment by horsdal** [comment]
The idea isn't that linker would add those query parameters - linker only builds up the URI based on the routes path. So I would do the same as you are doing in your situation - namely use linker to make a URI and then add the query parameters aftewards
